Исправлена позиция открепленных контролов. AUT-1294
samsmu/MITK pull request #177
Opened 2017-03-10 09:48 UTC by BlackCatter

http://samsmu.net:8083/browse/AUT-1294

Контролы больше не увеличиваются в размере при переключением между кейсами.

1. Перейти на универсальный кейс.
2. Открепить какой-нибудь контрол.
3. Перейти на вьювер и вернуться на универсальный кейс.

2017-03-10 11:16 UTC, mpkh commented
лучше коммиты делай более информативными, AUT добавляй второй строчкой

2017-03-11 08:23 UTC, Cynede requested changes
change commit message

2017-03-13 07:26 UTC, BlackCatter commented
Changed commit message

2017-03-13 07:31 UTC, Cynede approved these changes

2017-03-13 07:31 UTC, merged