Изменено поведение сохранения настроек для следующего файла. AUT-1851
samsmu/MITK pull request #179
Opened 2017-03-15 06:45 UTC by BlackCatter

http://samsmu.net:8083/browse/AUT-1851

При выборе опции "Apply to the next files with same type", выбранный вариант будет применяться ко всем последующим файлам такого же вида.

Чтение:
1. Открыть файл с выбором способа чтения
2. Поставить "Apply to the next files with same type"
3. Открыть файл еще раз

Запись:
1. Сохранить сегментацию
2. Выбрать при сохранении "Apply to the next files with same type"
3. Сохранить сегментацию еще раз

2017-03-15 06:58 UTC, KuznetsovAlexander requested changes
Я бы добавил префикс "m_" к статичным членам класса и перенес их в начало .cpp файла.

2017-03-16 06:25 UTC, mpkh commented
учесть, что при новом запуске автоплана настройки должны быть сохранены

2017-03-16 09:24 UTC, BlackCatter commented
Исправил ошибки стиля кода

2017-03-16 09:25 UTC, KuznetsovAlexander approved these changes

2017-03-16 10:27 UTC, mpkh commented
@KuznetsovAlexander @BlackCatter в этом модуле, кстати тоже нет berry, надо посмотреть есть ли входная точка из плагина для сохранения настроек, п.с. возможно не использовать статические поля, а каждый раз смотреть в настройки berry?

2017-03-16 10:38 UTC, KuznetsovAlexander commented
http://samsmu.net:8083/browse/AUT-1879 - задача про сохранение настроек.

MitkCore - модуль, там нет ни берри, ни Qt.
Вызывается это все из AutoplanUtilities, которое тоже модуль.
Я навскидку не вижу, как это решить, поэтому и попросил вынести эту проблему в отдельную задачу.

2017-03-16 15:59 UTC, merged