Исправлено обновление плагина объемной визуализации. AUT-1946
samsmu/MITK pull request #197
Opened 2017-04-03 13:42 UTC by BlackCatter

http://samsmu.net:8083/browse/AUT-1946

Плагин объемной визуализации теперь обновляет интерфейс если у выбраного нода был изменен параметр "volumerendering". Это необходимо, например, для корректного воставноления вью из вьюпорт тулбокса.

1. Сохранить состояние камеры
2. Включить Volume Rendering
3. Вернуть сохраненное состояние камеры

ОР: В плагине отображается корректоное значение для Volume Rendering

2017-04-03 13:52 UTC, KuznetsovAlexander requested changes

2017-04-03 13:52 UTC, KuznetsovAlexander commented on Plugins/org.mitk.gui.qt.volumevisualization/src/internal/QmitkVolumeVisualizationView.cpp
> +    bool temp;
Что-то дебажное осталось?

2017-04-03 13:55 UTC, BlackCatter commented
Убрал лишний код

2017-04-03 13:55 UTC, mechmaster commented on Plugins/org.mitk.gui.qt.volumevisualization/src/internal/QmitkVolumeVisualizationView.cpp
> +void QmitkVolumeVisualizationView::onPropertyChanged(const itk::Object *caller, const itk::EventObject & event)
А что будет, если ещё кто-то подписан на событие изменения свойств ноды к этой же ноде?

2017-04-03 13:57 UTC, KuznetsovAlexander approved these changes

2017-04-03 16:42 UTC, mpkh commented
@BlackCatter ты всегда делаешь rebase вместо корректировочного коммита?

2017-04-04 04:05 UTC, BlackCatter commented
@mpkh Да, если изменений мало и они не влияют на логику.

2017-04-04 06:06 UTC, merged