AutoplanExport: Dicom: Добавляет генерирование метаинфорцации для MITK.
samsmu/MITK pull request #208
Opened 2017-04-19 11:28 UTC by mechmaster

Данный PR добавляет следующее:

- Изменён способ хранения метаинформации в изображении. Теперь вся информация храниться в виде свойств изображения. Это позволяет сохранять метаинформацию в MITK.
- Добавлена генерация метаинформации. Это позволяет взять MITK, без метаинформации, и записать данные в DICOM. 

http://samsmu.net:8083/browse/AUT-1898

2017-04-19 12:00 UTC, KuznetsovAlexander requested changes

2017-04-19 12:00 UTC, KuznetsovAlexander commented on Modules/Core/src/DataManagement/mitkImage.cpp
> +
Получается, что workIndex == mainAxisIndex.

Но вообще весь этот кусок не нужен, потому что если мы загрузили дайком, то эта информация есть в его свойствах.
А если мы загрузили митк, то у нас главная ось всегда аксиальная.

2017-04-20 06:03 UTC, KuznetsovAlexander commented
mitkDicomSeriesReader.txx(137): error C2872: 'DicomTagToValueList': ambiguous symbol

2017-04-20 06:37 UTC, sergey-denisov commented on Modules/Core/src/DataManagement/mitkImage.cpp
> +  int index = 0;
int index = 2;
for (int i = 0; i < index; ++i) {
if (!!matrix[row][i]) {
index = i;
break;
}
}

2017-04-20 06:39 UTC, sergey-denisov commented on Modules/Core/src/DataManagement/mitkImage.cpp
> +        if (tagkey == std::string("0008|0016") || tagkey == std::string("0008|0018"))
tagkey и так std::string, зачем создавать лишний объект в правой части

2017-04-21 10:13 UTC, sergey-denisov approved these changes

2017-04-24 09:18 UTC, mechmaster commented
rebuild windows

2017-04-27 06:19 UTC, mechmaster commented
rebuild windows

2017-05-02 06:44 UTC, mpkh commented
rebuild windows

2017-05-02 06:45 UTC, mpkh commented
rebuild linux

2017-05-02 10:58 UTC, merged